spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://user_service_postgres:5432/user_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-request-size: 10MB
  config:
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    secret-key: ${JWT_SECRET_KEY}


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ru-central1
    endpoint:
      s3:
        static: https://storage.yandexcloud.net
    bucket:
      name: barbershop-app

server:
  port: 8080