spring:
  application:
    name: ${user.service.name}
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/user_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.service.host}:${eureka.service.port}/eureka/

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ru-central1
    endpoint:
      s3:
        static: https://storage.yandexcloud.net
    bucket:
      name: barbershop-app

server:
  port: ${user.service.port}